# Generated by Django 6.0.7 on 2026-08-23 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_feesetting_promotion'),
        ('workers', '0006_worker_latitude_worker_longitude_worker_work_range'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerPaymentAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('Outstanding Limit', 'Outstanding Limit')], default='Outstanding Limit', max_length=50)),
                ('outstanding_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('threshold_amount', models.DecimalField(decimal_places=2, default=200, max_digits=10)),
                ('sms_status', models.CharField(choices=[('Pending', 'Pending'), ('Sent', 'Sent'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('sms_sent_at', models.DateTimeField(blank=True, null=True)),
                ('sms_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_alerts', to='workers.worker')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
