# Generated by Django 6.0.7 on 2026-08-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_workerpaymentalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerpaymentalert',
            name='last_follow_up_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workerpaymentalert',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workerpaymentalert',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workerpaymentalert',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Follow-up', 'Follow-up'), ('Resolved', 'Resolved')], default='Pending', max_length=20),
        ),
    ]
