# Generated by Django 6.0.7 on 2026-09-16 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_workerpaymentalert_last_follow_up_at_and_more'),
        ('workers', '0007_alter_worker_profession'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerPaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Created', 'Created'), ('Pending', 'Pending'), ('Verified', 'Verified'), ('Failed', 'Failed'), ('Cancelled', 'Cancelled')], default='Created', max_length=20)),
                ('provider', models.CharField(blank=True, max_length=50)),
                ('provider_order_id', models.CharField(blank=True, max_length=150, null=True)),
                ('provider_payment_id', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='workers.worker')),
            ],
        ),
    ]
