# Generated by Django 6.0.7 on 2026-09-13 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileotp',
            name='consumed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
