# Generated by Django 6.0.7 on 2026-09-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_mobileotp_consumed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileotp',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('worker', 'Worker')], default='customer', max_length=10),
        ),
    ]
