# Generated by Django 6.0.7 on 2026-08-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customerprofile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='mobile_verified',
            field=models.BooleanField(default=False),
        ),
    ]
