# Generated by Django 6.0.7 on 2026-08-15 10:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_review_title_review_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='customer_offer',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AddField(
            model_name='booking',
            name='final_amount',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AddField(
            model_name='booking',
            name='negotiation_status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('Customer Offered', 'Customer Offered'), ('Worker Countered', 'Worker Countered'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Not Started', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='original_amount',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AddField(
            model_name='booking',
            name='worker_counter_offer',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
