# Generated by Django 6.0.7 on 2026-07-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('profession', models.CharField(choices=[('Plumber', 'Plumber'), ('Electrician', 'Electrician'), ('Carpenter', 'Carpenter'), ('Painter', 'Painter'), ('Mason', 'Mason'), ('Welder', 'Welder'), ('Cleaner', 'Cleaner'), ('Driver', 'Driver'), ('Other', 'Other')], max_length=30)),
                ('experience', models.PositiveIntegerField(help_text='Experience in years')),
                ('city', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('daily_wage', models.DecimalField(decimal_places=2, max_digits=8)),
                ('about', models.TextField(blank=True)),
                ('available', models.BooleanField(default=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='workers/')),
            ],
        ),
    ]
