# Generated by Django 6.0.7 on 2026-07-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_worker_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='verified',
        ),
        migrations.AddField(
            model_name='worker',
            name='vverified',
            field=models.BooleanField(default=False),
        ),
    ]
