# Generated by Django 6.0.7 on 2026-08-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0004_remove_worker_verified_worker_vverified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='profession',
            field=models.CharField(choices=[('Rajmistri', 'राजमिस्त्री'), ('Plumber', 'प्लम्बर'), ('Electrician', 'इलेक्ट्रिशियन'), ('Painter', 'पेंटर'), ('Carpenter', 'कारपेंटर'), ('Welder', 'वेल्डर'), ('Helper', 'हेल्पर'), ('AC Repair', 'AC रिपेयर')], max_length=30),
        ),
    ]
