# Generated by Django 6.0.7 on 2026-09-12 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0006_worker_latitude_worker_longitude_worker_work_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='profession',
            field=models.CharField(choices=[('Rajmistri', 'राजमिस्त्री'), ('Plumber', 'प्लम्बर'), ('Electrician', 'इलेक्ट्रिशियन'), ('Painter', 'पेंटर'), ('Carpenter', 'कारपेंटर'), ('Welder', 'वेल्डर'), ('Helper', 'हेल्पर'), ('AC Repair', 'AC रिपेयर'), ('Cleaner', 'क्लीनर'), ('Mechanic', 'मैकेनिक'), ('Driver', 'ड्राइवर'), ('House Maid', 'घरेलू सहायिका'), ('Cook', 'कुक'), ('Gardener', 'माली'), ('Labour', 'मजदूर'), ('Tiles Worker', 'टाइल्स वर्कर'), ('POP Worker', 'POP वर्कर'), ('Other', 'अन्य')], max_length=30),
        ),
    ]
